apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: ${artifactId}-ingress-grpc
spec:
  rules:
     - host: {{ .Values.deployment.host }}
       http:
        paths:
         - path: /org.apache.custos.identity.management.service.IdentityManagementService(/|$)(.*)
           backend:
              serviceName: identity-management-service
              servicePort: grpc

  tls:
    - hosts:
        - {{ .Values.deployment.host }}
      secretName: tls-secret