apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /log-management/$2
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: {{ .Values.deployment.host }}
      http:
        paths:
          - path: /log-management(/|$)(.*)
            backend:
              serviceName: log-management-service
              servicePort: envoyhttp

  tls:
    - hosts:
        - {{ .Values.deployment.host }}
      secretName: tls-secret